In [36]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from collections import Counter

In [37]:
iris = datasets.load_iris() 
X = iris.data
y = iris.target
names = iris.target_names

In [38]:
print(X[:5])
print(y[:5])
print(names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']


In [39]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [40]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))
#print(x_test[:10])

120
30
120
30


In [41]:
def euclidean(x, x2):
    sum=0
    for ix,ix2 in zip(x,x2):
        sum+=(ix-ix2)**2
    return np.sqrt(sum)

In [42]:
#euclidean([0,0], [3,4])

In [43]:
#xt=[5.1, 3., 4.2, 1.5]
xt=[1.0 ,2.0 ,3.0, 4.0]

In [44]:
dist={}
for i, x in enumerate(x_train):
    ed=euclidean(x, xt)
    dist[i]=ed


In [45]:
#print(dist)

In [46]:
sorted_d = sorted(dist.items(), key=lambda kv: kv[1])

In [47]:
print(sorted_d)

[(118, 4.9457052075512955), (73, 5.017967716117751), (86, 5.046781152378217), (111, 5.06951674225463), (29, 5.350700888668698), (6, 5.365631370118525), (34, 5.372150407425317), (61, 5.377731863899501), (63, 5.419409561935692), (80, 5.423098745182499), (119, 5.427706698044765), (117, 5.442425929675111), (69, 5.4671747731346585), (81, 5.468089245796927), (89, 5.507267925205746), (35, 5.508175741568165), (40, 5.511805511808268), (44, 5.514526271584895), (10, 5.534437640808684), (1, 5.537147279962851), (23, 5.55517776493246), (108, 5.5830099408831435), (56, 5.624055476255546), (71, 5.629387178015028), (88, 5.636488268416781), (18, 5.661271941887264), (21, 5.661271941887264), (57, 5.6780278266313555), (82, 5.680668974689513), (30, 5.687706040223949), (97, 5.687706040223949), (49, 5.718391382198319), (47, 5.727128425310541), (115, 5.754128952326321), (27, 5.762811813689564), (105, 5.779273310719955), (15, 5.790509476721371), (43, 5.808614292583043), (62, 5.8206528843421), (96, 5.827520913733

In [53]:
k=3
neighbors=[]
for i in range(k):
    neighbors.append(sorted_d[i][0])
print(neighbors)

[118, 73, 86]


In [54]:
classes=[ y_train[i] for i in neighbors]
print(classes)

[1, 1, 1]


In [55]:
count=Counter(classes)
print(count)

Counter({1: 3})


In [56]:
keys= list( count.keys() )
print('keys=', keys)
values=list( count.values() )
print('values=',values)

keys= [1]
values= [3]


In [57]:
index_of_max_values=values.index(max(values)) 
print('index of max value=', index_of_max_values)
y_hat=keys[index_of_max_values]
print('predict class=',y_hat)

index of max value= 0
predict class= 1
